# Generated by Django 2.1.7 on 2019-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('date', models.DateField()),
                ('case', models.ForeignKey(on_delete=None, to='cases.Cases')),
            ],
        ),
    ]
