# Generated by Django 2.1.7 on 2019-03-21 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_one',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lawyer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
