# Generated by Django 2.1.7 on 2019-03-30 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190330_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
