# Generated by Django 2.1.7 on 2019-03-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='label',
        ),
    ]
