# Generated by Django 2.1.7 on 2019-03-20 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chats_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='chats',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
