# Generated by Django 2.1.7 on 2019-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20190320_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
