# Generated by Django 2.1.7 on 2019-03-20 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20190320_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 12, 45, 58, 554602, tzinfo=utc)),
        ),
    ]
