# Generated by Django 2.1.7 on 2019-03-20 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_auto_20190320_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
